### ISSUE TITLE
##[error]Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}

### ISSUE THREAD

**Issue by rpbarlow** [Logerfo/gitflow-action#33]
Greetings!

I've been experimenting with this action in https://github.com/rpbarlow/test and I've been receiving an error message:

```
##[error]Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}
```

For example:

<img width="727" alt="Screen Shot 2020-04-15 at 11 36 27 AM" src="https://user-images.githubusercontent.com/61424078/79356841-5b393680-7f0d-11ea-82df-6c0a1b0fd90c.png">

That is with this config:

https://github.com/rpbarlow/test/blob/1a593e2c1b876c4a2f62d40e6151bcbc93fbe72c/.github/workflows/gitflow.yml

After some searching, it seems like this error can come from the GitHub API, but I am unsure of what is causing it. I'm curious if some of gitflow-action's dependencies might just need to be upgraded, or something along those lines?

**Comment by Logerfo** [comment]
I don't think I have ever seen this error before. Can you please enable [debug logging](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs) to narrow down the cause?

**Comment by bowlofeggs** [comment]
Hi @Logerfo!

I just sent you an e-mail with the full logs. I did find one traceback in one of the log files:

```
$ cat Worker_20200415-170019-utc.log 
[2020-04-15 17:00:20Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2020-04-15 17:00:20Z INFO Worker] Version: 2.168.0
[2020-04-15 17:00:20Z INFO Worker] Commit: 9ed9e7a6730db3f4e83900620d4ac3c00ff3e775
[2020-04-15 17:00:20Z INFO Worker] Culture: 
[2020-04-15 17:00:20Z INFO Worker] UI Culture: 
[2020-04-15 17:00:20Z ERR  Worker] System.IO.IOException: Invalid pipe handle.
   at System.IO.Pipes.PipeStream.ValidateHandleIsPipe(SafePipeHandle safePipeHandle)
   at System.IO.Pipes.AnonymousPipeClientStream.Init(PipeDirection direction, SafePipeHandle safePipeHandle)
   at System.IO.Pipes.AnonymousPipeClientStream..ctor(PipeDirection direction, String pipeHandleAsString)
   at GitHub.Runner.Common.ProcessChannel.StartClient(String pipeNameInput, String pipeNameOutput)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

Other than that and the original error message I reported above, I didn't see any further information that seemed relevant.

**Comment by rpbarlow** [comment]
Hi @Logerfo!

I just sent you an e-mail with the full logs. I did find one traceback in one of the log files:

```
$ cat Worker_20200415-170019-utc.log 
[2020-04-15 17:00:20Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2020-04-15 17:00:20Z INFO Worker] Version: 2.168.0
[2020-04-15 17:00:20Z INFO Worker] Commit: 9ed9e7a6730db3f4e83900620d4ac3c00ff3e775
[2020-04-15 17:00:20Z INFO Worker] Culture: 
[2020-04-15 17:00:20Z INFO Worker] UI Culture: 
[2020-04-15 17:00:20Z ERR  Worker] System.IO.IOException: Invalid pipe handle.
   at System.IO.Pipes.PipeStream.ValidateHandleIsPipe(SafePipeHandle safePipeHandle)
   at System.IO.Pipes.AnonymousPipeClientStream.Init(PipeDirection direction, SafePipeHandle safePipeHandle)
   at System.IO.Pipes.AnonymousPipeClientStream..ctor(PipeDirection direction, String pipeHandleAsString)
   at GitHub.Runner.Common.ProcessChannel.StartClient(String pipeNameInput, String pipeNameOutput)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

Other than that and the original error message I reported above, I didn't see any further information that seemed relevant.

**Comment by Logerfo** [comment]
I think this will show up to your runner instance for whatever error the action gets.
I don't see any debug information on the logs you sent me. Did you set the secret as explained on the documentation I referred to on my last comment? I don't expect it to have information on the error itself, but on which part of the code the action fails.

**Comment by rpbarlow** [comment]
@Logerfo I did set the secret to true, and I see the secret being echoed in one of the logs:

```
$ grep -A 3 ACTIONS_RUNNER_DEBUG < Worker_20200415-170044-utc.log 
    "ACTIONS_RUNNER_DEBUG": {
      "value": "true",
      "isSecret": true
    },
```

**Comment by rpbarlow** [comment]
I checked the logs from a run that happened before I set that variable, and the entire ```runner-diagnostic-logs``` folder was not present in that one, so I believe that the ```ACTIONS_RUNNER_DEBUG``` variable is set correctly is the logs I sent you. According to the GitHub docs, that folder is created when that setting is in place.

**Comment by rpbarlow** [comment]
@Logerfo I figured it out - this is what happens if you use the wrong name for the dev branch:

https://github.com/rpbarlow/test/pull/6/commits/fd0a38a949d2aed128ef98dfd9407bfa3de1339e

So, it was an error in my config ☺

I suggest perhaps a clearer error message in case someone else makes this mistake in the future. I'll file a new ticket to express that idea.
