### ISSUE TITLE
Missing index.js Error

### ISSUE THREAD

**Issue by jjkirby** [Logerfo/gitflow-action#63]
Running your latest  Logerfo/gitflow-action@0.0.5.  I get this error when executing:

Run Logerfo/gitflow-action@0.0.5
  with:
    github-token: ***
    release: test-13
    release-regex: ^release/(.*)
    dev: develop
    master: main
    label: gitflow
    auto-merge: false
    require-merge: false
Error: File not found: '/home/runner/work/_actions/Logerfo/gitflow-action/0.0.[5](https://github.com/factioninc/test-repo/actions/runs/3222786295/jobs/5272214399#step:3:5)/dist/index.js'

**Comment by Logerfo** [comment]
You're right, thank you for reporting. I messed up the release process. It's been a while... almost three years without releasing.  
I pushed up to `release` and `0.0.5` again. Can you retry, please?

**Comment by jjkirby** [comment]
Nope:

/home/runner/work/_actions/Logerfo/gitflow-action/0.0.5/dist/index.js:346
    client = new github.GitHub(token);
             ^

TypeError: github.GitHub is not a constructor
    at Object.31 (/home/runner/work/_actions/Logerfo/gitflow-action/0.0.5/dist/index.js:346:14)
    at __webpack_require__ (/home/runner/work/_actions/Logerfo/gitflow-action/0.0.5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/Logerfo/gitflow-action/0.0.5/dist/index.js:43:19)
    at /home/runner/work/_actions/Logerfo/gitflow-action/0.0.5/dist/index.js:47:18
    at Object.<anonymous> (/home/runner/work/_actions/Logerfo/gitflow-action/0.0.5/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:[12](https://github.com/factioninc/test-repo/actions/runs/3222945077/jobs/5272524560#step:3:13))

**Comment by Logerfo** [comment]
Hmm, seems like a breaking change at @actions/github. I've made a new change for both release and 0.0.5, but I'm currently without a testing environment, so your feedback is very welcome.
